### ISSUE TITLE
使用谷歌高级语法时的bug，另外再提点小建议

### ISSUE THREAD

**Issue by AdiEcho** [ShangRui-hash/url-collector#2]
**bug内容**
运行` -k "你好 site:.com" `时会立刻结束程序，运行 ` -k "你好site:.com" ` 则正常

**需要添加的功能内容**
1. 添加debug输出，在出现这个bug时我一直以为我的ip被限制了，后来排查才发现是-k的问题
2. 添加单行显示采集url的功能，可通过覆盖输出达成
3. 添加显示当前的采集进度

**Comment by ShangRui-hash** [comment]
okk 收到，感谢你的支持和建议，目前正在改进中
